# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c81e92181316c0357ed2f64e207bc432f6ddd021cd0d987bd16477fd05f527d5de4c79db306511a4fcbca7cc0b1dd4c1db0b120374452ca161098aa70601808

test:
  secret_key_base: b3eff17fc81a0f61442dcb89864d65dd1b70dba876f7d69a0af63460179faf262106ccb06582e66720f29a25c7dc2d7debf83e7fb3fff396aca104cd58247145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
